### ISSUE TITLE
Information about the source of the data

### ISSUE THREAD

**Issue by LuigiCerone** [SirPopiel/OptimalAmbulancePositioning#1]
Hi,
can you please share the source of the data and better explain the meaning of the file "lpcm.dat"?
Thanks.

**Comment by SirPopiel** [comment]
Hello, I was given the data by my operations' research professor, it is based on the 118's Milan data from 2005. The lpcm.dat file contains the two matrixes of coverage of the city's zones (8 mins and 20 mins) and it contains stats about the number of incidents in every place and so on, useful to estimate the demand of the various spots. :)
